### ISSUE TITLE
call is not a function

### ISSUE THREAD

**Issue by adwen2010** [hpb-project/web3.js#1]
hi , i use web3.js to call a contract funciton , my code just like this:

var zsc = '0x51c9cf105cf927f12e188c0d2683dc29077125b3';
const zscContract = new web3_hpb.hpb.contract(ZSC.abi).at(zsc);
console.log("epochlength:",zscContract.epochLength.call());

then ,report an error:
TypeErrro:this._eth.call is not a function 
        at SolidityFunction.call (/home/bj/go/src/github.com/hpb-project/web3.js/node_modules/web3/lib/web3/function.js:135:32)
    at Object.<anonymous> (/home/bj/go/src/github.com/hpb-project/web3.js/example.js:41:37)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

systeminfo: 
ubuntu 18.04
node : v12.18.0

**Comment by Nicemanss** [comment]
Can you try changing your code to this please (not using "new" keyword while binding the contract):

var zsc = '0x51c9cf105cf927f12e188c0d2683dc29077125b3';  

const zscContract = web3_hpb.hpb.contract(ZSC.abi).at(zsc);  

console.log("epochlength:",zscContract.epochLength.call());

**Comment by adwen2010** [comment]
yes, it works without "new" .thanks.
